# Generated by Django 5.1.1 on 2024-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('title_link', models.CharField(max_length=150, null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='static/slider/')),
                ('title', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
