# Generated by Django 5.1.1 on 2024-10-26 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_jobs_tbl_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, null=True)),
                ('city_picture', models.ImageField(null=True, upload_to='static/city/')),
            ],
        ),
        migrations.CreateModel(
            name='video_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_headline', models.CharField(max_length=400, null=True)),
                ('news_description', models.TextField(null=True)),
                ('video_link', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=400, null=True)),
                ('news_description', models.TextField(null=True)),
                ('Posted_date', models.DateField()),
                ('news_picture', models.ImageField(null=True, upload_to='static/news/')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
                ('news_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_city')),
            ],
        ),
    ]
