# Generated by Django 5.1.1 on 2024-11-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tbl_city_video_news_tbl_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_qus', models.CharField(max_length=600, null=True)),
                ('faq_ans', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tbl_news',
            old_name='Posted_date',
            new_name='posted_date',
        ),
    ]
