# Generated by Django 5.1.1 on 2024-11-02 07:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tbl_faq_rename_posted_date_tbl_news_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_news',
            name='news_description',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='video_news',
            name='news_description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
