# Generated by Django 5.1.1 on 2024-11-07 06:06

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_video_news_posted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_picture', models.ImageField(null=True, upload_to='static/investor/')),
                ('in_name', models.CharField(max_length=100, null=True)),
                ('in_description', tinymce.models.HTMLField(null=True)),
            ],
        ),
    ]
